# Linear Algebra for Machine Learning - Exercises

This colab supports the exercises in the [slides](https://gmesch.github.io/math21/slides.html).

In [ ]:
import numpy as np
import numpy.linalg as la

## Axioms of Vector Space
[slide](https://gmesch.github.io/math21/slides.html#slide=exercise1)

Are these two examples of vector spaces?
   * Tuples of Rational Numbers over Real Numbers?
   * Tuples of Real Numbers over Rational Numbers?

## Linear Independence
[slide](https://gmesch.github.io/math21/slides.html#slide=exercise2)

Imagine sets of arrows that are
   * linearly independent,
   * linearly dependent.

## Coordinate Tuples vs F^n Vectors
[slide](https://gmesch.github.io/math21/slides.html#slide=exercise3)

Define two different bases in R^2 and compute the coordinates of one vector [1, 1] in both bases.

Vector

In [ ]:
v = np.array([1,1])


Basis

In [ ]:
basis_1 = np.array([[1,3],[3,1]])
basis_2 = np.array([[1,0],[0,1]])

Coordinates of the Vector in either Basis

In [ ]:
coord_1 = np.array([1/4,1/4])
coord_2 = np.array([1,0])

The coordinates multipled by the basis yield the vector
in either basis.

In [ ]:
coord_1 @ basis_1

array([1., 1.])

In [ ]:
coord_2 @ basis_2

array([1, 0])

The same vector has *different* coordinates in *different* bases.

Both vectors and their coordinates are tuples of numbers, but we must not confuse them!

## Basis Transformation
[slide](https://gmesch.github.io/math21/slides.html#slide=exercise4)

Write down the basis transformation and the coordinate transformation for the transition between Basis 1 and Basis 2 in the previous exercise.

Write down vector as coordinates and basis in Einstein notation. Notice that there is a function in numpy, `np.einsum` that allows to express summation over indices according to the Einstein convention.

In [ ]:
np.einsum('i,i...', coord_1, basis_1)

array([1., 1.])

In [ ]:
np.einsum('i,i...', coord_2, basis_2)

array([1, 0])

This is the Basis Transformation from Basis 1 to Basis 2

In [ ]:
Tb = np.array([[-1/8, 3/8], [3/8, -1/8]])

Express Basis 2 from Basis 1
This yields basis 1:

In [ ]:
np.einsum('ij,j...', Tb, basis_1)

array([[1., 0.],
       [0., 1.]])

The coordinates transform differently

In [ ]:
Tc = [[1,3],[3,1]]
np.einsum('ij,j', Tc, coord_1)

array([1., 1.])

The basis and coordinate transformations are each other's inverse:

In [ ]:
np.einsum('ij,jk', Tb, Tc)

array([[1., 0.],
       [0., 1.]])

## Scalar Product and Metric Tensor
[slide](https://gmesch.github.io/math21/slides.html#slide=exercise5)

Write down the coordinates of the scalar product for tuples from R^2 in the two bases from the previous exercise.

Vectors and Basis vectors in both bases

In [ ]:
v = np.array([1,1])
w = np.array([1,0])

e1 = np.array([1,3])
e2 = np.array([3,1])

basis_1 = np.array([e1, e2])

e1p = np.array([1,0])
e2p = np.array([0,1])

basis_2 = np.array([e1p, e2p])

Write down the coordinates of the scalar product in both bases

In [ ]:
g = np.array([[np.dot(e1,e1), np.dot(e1,e2)],
              [np.dot(e2,e1), np.dot(e2,e2)]])
g

array([[10,  6],
       [ 6, 10]])

In [ ]:
gp = np.array([[np.dot(e1p,e1p), np.dot(e1p,e2p)],
              [np.dot(e2p,e1p), np.dot(e2p,e2p)]])
gp

array([[1, 0],
       [0, 1]])

The scalar product of the vectors can be expressed either directly, or using the coordinates.

Here are the coordinates of both vectors in both bases:

In [ ]:
v_coord_1 = np.array([1/4, 1/4])
np.einsum('i,i...', v_coord_1, basis_1)

array([1., 1.])

In [ ]:
w_coord_1 = np.array([-1/8, 3/8])
np.einsum('i,i...', w_coord_1, basis_1)

array([1., 0.])

In [ ]:
v_coord_2 = np.array([1, 1])
np.einsum('i,i...', v_coord_2, basis_2)

array([1, 1])

In [ ]:
w_coord_2 = np.array([1, 0])
np.einsum('i,i...', w_coord_2, basis_2)

array([1, 0])

Now we can write the scalar product as direct dot product, or using the coordinates of the scalar product in either basis:

In [ ]:
np.dot(v, w)

1

In [ ]:
np.einsum('i,j,ij', w_coord_1, v_coord_1, g)

1.0

In [ ]:
np.einsum('i,j,ij', w_coord_2, v_coord_2, gp)

1